# Generated by Django 2.2.6 on 2019-12-06 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='playlist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date and time this page was created. Automatically generated when the model saves.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date and time this page was updated. Automatically generated when the model updates.'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='slug',
            field=models.CharField(blank=True, editable=False, help_text='Unique URL path to access this playlist. Generated by the system.', max_length=600),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='author',
            field=models.ForeignKey(help_text='The user that posted this playlist.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(help_text='Write the description of your playlist here.'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_name',
            field=models.CharField(help_text='Title of your page.', max_length=600, unique=True),
        ),
    ]
